### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by shadowTW** [xFutte/qb-newspaper#4]
![image](https://user-images.githubusercontent.com/64441627/179356169-2465cab8-3b72-4d3a-bafe-03a227c01b4d.png)
when I try to buy a news paper

**Comment by xFutte** [comment]
@shadowTW I made some changes to the database yesterday. Try to reclone the issue, and recreate your database table. I added "publisher" to the database. Let me know if it works.

**Comment by xFutte** [comment]
I'll look into it.

**Comment by xFutte** [comment]
Issue has been resolved. Update and it should work.
