### ISSUE TITLE
html doesn't show up

### ISSUE THREAD

**Issue by shadowTW** [xFutte/qb-newspaper#5]
https://streamable.com/2b9cp1

**Comment by xFutte** [comment]
@shadowTW Any error outputs? Otherwise try to reclone the repo. Just updated some stuff.

**Comment by xFutte** [comment]
Also, did you run "npm install" in the ./web directory?

**Comment by xFutte** [comment]
Neither in the client and server console?

**Comment by xFutte** [comment]
Is everything compiled? Try running "npm run dev" in the ./web directory. That will bundle everything.

**Comment by xFutte** [comment]
I can see that the bundle folder is missing here in Github, for some reason - that's the reason. Do the above and hopefully it should work for you.
