### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by shadowTW** [xFutte/qb-newspaper#6]
![image](https://user-images.githubusercontent.com/64441627/180432390-e03aa82d-adb6-4dbd-9468-d3f97b2e6956.png)
i get this while im trying to open the news papaer

**Comment by xFutte** [comment]
Have you followed the setup steps in the README file?

**Comment by xFutte** [comment]
What level have you set the player to be as a reporter?

**Comment by xFutte** [comment]
> I got no job and it doesn't open it and yes I followed all the steps from readme

I'll look into it.

**Comment by xFutte** [comment]
@shadowTW I just pushed a lot of changes, including a possible fix. Please pull the repo and see if it helps.

**Comment by xFutte** [comment]
@shadowTW Let me know if it helped
